package com.example.spring1.infrastructure.mybatis;

public class AccountManagement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account_management.id
     *
     * @mbg.generated Mon Jul 08 22:42:28 JST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account_management.name
     *
     * @mbg.generated Mon Jul 08 22:42:28 JST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.account_management.id
     *
     * @return the value of public.account_management.id
     *
     * @mbg.generated Mon Jul 08 22:42:28 JST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.account_management.id
     *
     * @param id the value for public.account_management.id
     *
     * @mbg.generated Mon Jul 08 22:42:28 JST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.account_management.name
     *
     * @return the value of public.account_management.name
     *
     * @mbg.generated Mon Jul 08 22:42:28 JST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.account_management.name
     *
     * @param name the value for public.account_management.name
     *
     * @mbg.generated Mon Jul 08 22:42:28 JST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}